services:
  db:
    image: postgres:16-alpine
    container_name: pgs_task
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - br-postgresql:/var/lib/postgresql/data

  task:
    image: task:1.0
    container_name: app_task
    depends_on:
      - db
      - migrate
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "8080:8080"

  migrate:
    image: gomicro/goose:3.26.0
    depends_on:
      - db
    volumes:
      - ./internal/migrations:/migrations
    command: >
      sh -c "goose -dir /migrations postgres 'postgres://app:app@db:5432/app?sslmode=disable' up ."
    restart: "no"

volumes:
  br-postgresql: